### ISSUE TITLE
Does it ignore .babelrc?

### ISSUE THREAD

**Issue by TobiasBales** [aki77/atom-source-preview-babel#2]
I just tried using it but I get syntax errors when enabling it due to using stage-0 in my project.

My guess would be, that the plugin ignores the projects .babelrc, is that correct?

**Comment by aki77** [comment]
Please try language-babel out once too.

https://github.com/gandm/language-babel#previewing

**Comment by TobiasBales** [comment]
When I disable this package it does work, yes
