### ISSUE TITLE
Clashes with language-babel

### ISSUE THREAD

**Issue by gandm** [aki77/atom-source-preview-babel#4]
Both this package and language-babel act as babel providers but also use the same `fromGrammarName` and `fromScopeName`. If both are loaded it causes issues as they contend for the same compile. language-babel is also the source of the grammar and hence the grammar cannot be changed. Additionally, language-babel supports babel v5 and v6 and this package doesn't. Is there any chance this package can be changed to point to another grammar name or maybe be removed entirely?

**Comment by aki77** [comment]
Thank you for proposal.
Let me think about it.

**Comment by aki77** [comment]
Updated README.
language-babel is great package!
Thank you! 😃

**Comment by gandm** [comment]
Thanks. Kudos to you for source-preview.
